### PR TITLE
Add ObjectIdField and fix version bug in doc_requirement.txt

### PR DESCRIPTION
**Pull request by cula**
Can I add ObjectIdField? It maybe used easily to store info of other model's '_id' field.

### CODE REVIEW

**Comment by cula** [comment]
Hi,
what can I do to promote this merge? I mean, I can fix what is wrong.

**Comment by cula** [comment]
update pymongo&motor versions #107 

Oh， version problems also fixed in this issue.   Thx @etataurov

**Comment by cula** [comment]
Oh closed for mistake.

Update Info:

Version problems also fixed in #107 . Thx  @etataurov.

**Comment by heynemann** [comment]
Why do you need this?

**Comment by etataurov** [comment]
Personally, I have two cases for ObjectIdField:
 - store id of file in GridFS
 - store a reference to some object, when all I need is just id (there is no straightforward way to get objectId from ReferenceField, as far as I know)

**Pull request merged**
